name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: npm ci

    - uses: lannonbr/vsce-action@master
      with:
        args: "package --out vscode-ghc-simple.vsix"
    - uses: actions/upload-artifact@v1.0.0
      with:
        name: vscode-ghc-simple.vsix
        path: vscode-ghc-simple.vsix

    - uses: lannonbr/vsce-action@master
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      with:
        args: "publish -p $VSCE_TOKEN"
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
